# Generated by Django 4.2 on 2023-04-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.IntegerField(blank=True, choices=[(1, 'LEONARDO HENRIQUE FURLAN E SILVA 12354888619')], verbose_name='Clientes')),
                ('nome_documento', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
    ]
