# Generated by Django 4.2 on 2023-04-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'LEONARDO HENRIQUE FURLAN E SILVA 12354888619'), (2, 'ISABELY GABRIELA JESUS DOS SANTOS E SILVA')], verbose_name='Clientes'),
        ),
    ]
