# Generated by Django 4.2 on 2023-04-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documentos_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Documento',
        ),
    ]
