# Generated by Django 4.2 on 2023-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.IntegerField(blank=True, choices=[(1, 'LEONARDO HENRIQUE FURLAN E SILVA 12354888619'), (2, 'ISABELY GABRIELA JESUS DOS SANTOS E SILVA'), (3, 'Leo teste 1 LTDA')], verbose_name='Clientes'),
        ),
    ]
